### ISSUE TITLE
时间没有到就再等15s是否有问题

### ISSUE THREAD

**Issue by dpinthinker** [CNU105/BUY-HW#4]
https://github.com/CNU105/BUY-HW/blob/087604ea40235c02b77961fd53121c79f8ebacfc/demo.py#L94

是否快到时间的时候，再等15s时间错过抢购时间了？

**Comment by XYZliang** [comment]
是的，我基于这个项目重写了这个脚本在[HUAWEI-STORE-GO](https://github.com/XYZliang/HUAWEI-STORE-GO)，这个地方修改了
