### ISSUE TITLE
账号密码不能输入

### ISSUE THREAD

**Issue by YuanTao1995** [CNU105/BUY-HW#6]
Python3.7 + selenium3.141.0 + Chrome 87.0.4280.88 + chromedriver版本忘记了
可以打开网页, 但无法输入账号密码, 超时之后就报异常: 账号密码不能输入

**Comment by FangYang970206** [comment]
@YuanTao1995 我也刚遇到了这个问题，请问你解决了吗？

**Comment by zxl333** [comment]
我也遇到了，同问 @YuanTao1995

**Comment by XYZliang** [comment]
> 我也遇到了，同问@ YuanTao1995
> @ YuanTao1995我也刚遇到了这个问题，请问你解决了吗？
网页已经改版了，原来的已经不可用。
我基于这个项目重写了这个脚本在[HUAWEI-STORE-GO](https://github.com/XYZliang/HUAWEI-STORE-GO)

**Comment by XYZliang** [comment]
网页已经改版了，原来的已经不可用。
我基于这个项目重写了这个脚本在[HUAWEI-STORE-GO](https://github.com/XYZliang/HUAWEI-STORE-GO)
